In [1]:
import torch

In [2]:
import torch.nn.functional as F

# Temperature Softmax

In [14]:
predictions = torch.log(torch.rand(3))

In [15]:
predictions

tensor([-1.2623, -0.4757, -0.7656])

In [18]:
print (F.softmax(predictions, dim= -1))
print (F.softmax(predictions / 0.5, dim= -1))
print (F.softmax(predictions / 0.1, dim= -1))
print (F.softmax(predictions / 10, dim= -1))
print (F.softmax(predictions / 100, dim= -1))

tensor([0.2066, 0.4538, 0.3396])
tensor([0.1173, 0.5658, 0.3168])
tensor([3.6340e-04, 9.4747e-01, 5.2169e-02])
tensor([0.3192, 0.3453, 0.3355])
tensor([0.3319, 0.3345, 0.3336])


# MSE Loss

In [3]:
prediction = torch.randn(4,5)

In [4]:
label = torch.randn(4,5)

In [13]:
mse = nn.MSELoss(reduction='sum')

In [14]:
loss = mse(prediction,label)

In [15]:
print(prediction)
print(label)
print(loss)

tensor([[ 0.5326, -0.1498,  1.4755, -0.2914,  0.8742],
        [-2.7824, -0.8570,  0.9279, -0.0916, -0.3933],
        [-0.1473, -2.1336, -0.8009,  0.8989, -0.2139],
        [ 2.4772, -0.6475,  0.7765, -1.6998, -1.2019]])
tensor([[-0.1635, -1.1870, -0.9581,  0.7810,  1.1455],
        [-0.0581,  0.5747, -0.7705,  1.2953,  0.3170],
        [-0.2140,  1.3739, -0.5246, -1.2595, -0.9864],
        [ 0.8756, -0.4345,  2.6081, -1.2109,  0.4161]])
tensor(49.9513)


# BCE Loss

In [19]:
label = torch.zeros(4,5).random_(0,2)

In [20]:
label

tensor([[1., 0., 1., 1., 1.],
        [0., 1., 0., 0., 1.],
        [1., 1., 0., 0., 1.],
        [0., 0., 1., 1., 0.]])

In [21]:
sigmoid = nn.Sigmoid()

In [23]:
bce = nn.BCELoss(reduction='mean')

In [24]:
bce(sigmoid(prediction),label)

tensor(0.8748)

In [25]:
bces = nn.BCEWithLogitsLoss(reduction='mean')

In [26]:
bces(prediction,label)

tensor(0.8748)