In [1]:
import torch
import torch.nn as nn

In [8]:
layer = nn.Linear(5,5)

In [9]:
layer.weight#.data

Parameter containing:
tensor([[ 0.1535, -0.0401, -0.3115,  0.1727,  0.3661],
        [ 0.1338, -0.0458,  0.3218,  0.2063,  0.3026],
        [ 0.2302,  0.3301,  0.0239, -0.2335,  0.4186],
        [ 0.2914,  0.2052,  0.4091,  0.0786, -0.2057],
        [ 0.3258, -0.2174, -0.0754, -0.1014,  0.2070]], requires_grad=True)

In [6]:
nn.init.uniform_(layer.weight, a=0.0, b=3.0)

Parameter containing:
tensor([[2.9008, 1.1519, 1.7501, 0.9784, 1.5840],
        [1.8396, 0.8440, 2.6456, 1.7860, 2.5136],
        [0.1932, 0.7469, 2.5330, 0.0673, 1.4136],
        [0.2156, 2.5830, 0.8729, 1.4029, 1.4747],
        [2.2144, 1.9747, 0.2746, 1.5851, 0.4794]], requires_grad=True)

In [13]:
nn.init.normal_(layer.weight, mean=0.0, std=0.2)

Parameter containing:
tensor([[ 0.0747, -0.3922,  0.1329, -0.3682, -0.2176],
        [ 0.1552, -0.0379,  0.1975,  0.0530,  0.1264],
        [-0.3383, -0.0057, -0.1053, -0.2954, -0.0159],
        [ 0.1727, -0.0776, -0.0130,  0.0889,  0.0356],
        [ 0.0595, -0.1553,  0.1069,  0.1260,  0.1040]], requires_grad=True)

In [14]:
nn.init.constant_(layer.bias, 3)

Parameter containing:
tensor([3., 3., 3., 3., 3.], requires_grad=True)

In [ ]:
nn.init.xavier_uniform_(layer.weight, gain=1.0)